### ISSUE TITLE
Create a 3D model of a balcony

### ISSUE THREAD

**Issue by themangokid** [themangokid/tk20_smart_homes#34]
Create a model and add materials

**Comment by adriantk20** [comment]
![saul](https://user-images.githubusercontent.com/84010287/203560224-0c41a08a-dfcf-4f85-912f-c1722f9fae6b.jpeg)
Blacony yes

**Comment by adriantk20** [comment]
![image](https://user-images.githubusercontent.com/84010287/203560684-f978edd0-f34d-4566-a787-dc8b3f5259ee.png)
Baclnopny
Real

**Comment by adriantk20** [comment]
rael bblacony
